# Generated by Django 5.2.1 on 2025-06-07 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=120)),
                ('recipe', models.TextField()),
                ('cost', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('tables', models.IntegerField()),
                ('taken', models.IntegerField()),
                ('avail', models.IntegerField()),
                ('guests', models.IntegerField()),
                ('staff', models.IntegerField()),
                ('waiting', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table', models.IntegerField()),
                ('guests', models.IntegerField()),
                ('total', models.FloatField()),
                ('finalized_list', models.JSONField()),
                ('completed', models.BooleanField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.location')),
            ],
        ),
        migrations.CreateModel(
            name='AddItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=120)),
                ('recipe', models.TextField()),
                ('unit_price', models.FloatField()),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
                ('guest', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
