# Generated by Django 5.2.1 on 2025-06-07 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additem',
            old_name='recipe',
            new_name='modification',
        ),
    ]
